version: '3.8'

services:
  auth:
    build: ./auth_ms
    command: /monjjubot/auth/auth_server/main
    ports:
      - 59755:59755
    depends_on:
      - bot
      - database
      - mailer
      - server
      - web

  bot:
    build: ./bot_ms
    command: /monjjubot/bot_app/main
    ports:
      - 59756:59756

  database:
    build: ./database_ms
    command: /monjjubot/database/database_server/main
    ports:
      - 59754:59754
    depends_on:
      data:
        condition: service_healthy

  mailer:
    build: ./mailer_ms
    command: /monjjubot/mailer/mail_server/main
    ports:
      - 59752:59752

  server:
    build: ./server_ms
    command: /monjjubot/main_server/server/main
    ports:
      - 59751:59751

  web:
    build: ./website_ms
    command: /monjjubot/website/main
    ports:
      - 59753:59753



  data:
    restart: always
    image: postgres:latest
    env_file:
      - database.env
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/:/docker-entrypoint-initdb.d/

volumes:
  postgres-data:
